# ▒█▀▀█ █▀▀█ █░░ █▀▀█ █▀▀█ █▀▀ 
# ▒█░░░ █░░█ █░░ █░░█ █▄▄▀ ▀▀█ 
# ▒█▄▄█ ▀▀▀▀ ▀▀▀ ▀▀▀▀ ▀░▀▀ ▀▀▀


$wallpaper={wallpaper}

$background            = rgb(111319)
$foreground            = rgb(e2e2eb)

$color0 = rgb(111319)
$color1 = rgb(ffb4ab)
$color2 = rgb(f8acff)
$color3 = rgb(b6c6f2)
$color4 = rgb(b0c6ff)
$color5 = rgb(f8acff)
$color6 = rgb(b6c6f2)
$color7 = rgb(e2e2eb)
$color8 = rgb(8d909e)
$color9 = rgb(ffb4ab)
$color10 = rgb(f8acff)
$color11 = rgb(b6c6f2)
$color12 = rgb(b0c6ff)
$color13 = rgb(f8acff)
$color14 = rgb(b6c6f2)
$color15 = rgb(e2e2eb)
