command_timeout = 5000
add_newline = true


format = '''$os$directory$git_branch$git_status$character'''
right_format = "$python$java$kotlin$nodejs$c$cmd_duration"

[os]
disabled = false
format = '[](blue)[ $symbol ](bg:blue fg:black)[](blue)'

[os.symbols]
Arch = "󰣇 "

[directory]
truncation_length = 1
format = "[](fg:black bg:red)[ $path ](bg:red)[](fg:red)"


[git_branch]
symbol = ' '
format = "[](fg:black bg:green)[ $symbol$branch ](fg:black bg:green)"

[git_status]
conflicted = ' '
up_to_date = ' '
untracked = ' '
ahead = '⇡$count'
diverged = '⇅ ⇡${ahead_count}⇣${behind_count}'
behind = '⇣$count'
stashed = '󰏗 '
modified = '󰷈 '
staged = '[++$count ](green)'
renamed = ' '
deleted = ' '
style = 'bold green'
format = '[\(($all_status$ahead_behind)\) ](fg:black bg:green)[](fg:green)'


[character]
format = "[](fg:black bg:yellow)[ $symbol ](fg:black bg:yellow)[](yellow) "
success_symbol = ""
error_symbol = ""

# right prompt
[fill]
symbol = ' '

# languages
[python]
symbol = ' '
style = 'bold yellow'
format = '[$symbol$virtualenv]($style) '

[java]
symbol = ' '
style = 'bold red'
format = '[$symbol]($style) '

[kotlin]
symbol = ' '
style = 'bold purple'
format = '[$symbol]($style) '

[nodejs]
symbol = ' '
format = '[$symbol](bold dimmed green) '

[c]
symbol = ' '
style = 'bold dimmed purple'
format = '[$symbol]($style) '

[cmd_duration]
min_time = 1
show_milliseconds = true
format="[$duration]($style)"
style = "bold purple"
